### ISSUE TITLE
Navigation Pane crash

### ISSUE THREAD

**Issue by MilesFarber** [MilesFarber/Windows10SuperCharger#1]
Third party programs still cause explorer to crash when selecting a file. This is caused by the fact the navigation pane is still being turned on, entirely ignoring [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Modules\GlobalSettings\Sizer]. This is not caused by the script or Windows, but rather by the third party program ignoring the key above for no reason whatsoever.

**Comment by FlarosOverfield** [comment]
![image](https://user-images.githubusercontent.com/24918282/155851115-25f89bc5-820c-4886-bd20-972fc927a690.png)
This is fixed by opening File Explorer, opening the navigation pane, disabling "Show All Libraries" and "Show All Folders", uncollapsing all five elements, and closing the navigation pane. This should be automated by the powershell file.

**Comment by FlarosOverfield** [comment]
Nope, started doing it again.

**Comment by FlarosOverfield** [comment]
Bug seems to inexplicably disappear after updating to the latest version of windows
